apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: kubebot
  name: kubebot-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: manual
