---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-prod-system
  namespace: prod
spec:
  interval: 18s
  ref:
    branch: prod
  secretRef:
    name: flux-system
  url: ssh://git@github.com/obezsmertnyi/flux-image-updates.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-prod-system
  namespace: prod
spec:
  interval: 20s
  path: ./clusters/kbot/prod
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-prod-system
