apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  namespace: kubebot
  name: kubebot-secret
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
  target:
    name: {{ .Values.externalSecret.target.name }}
    template:
      engineVersion: v2
      data:
        {{- range $key, $val := .Values.externalSecret.data }}
        {{ $val.secretKey }}: "{{ `{{ .` }}{{ $val.secretKey }}{{ ` | toString }}` }}"
        {{- end }}
  data:
    {{- range .Values.externalSecret.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteRef.key }}
        property: {{ .remoteRef.property }}
    {{- end }}
