{{- range .Values.roles }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .name }}-binding
  namespace: {{ .namespace }}
subjects:
- kind: ServiceAccount
  name: {{ $.Values.serviceAccountName }}
  namespace: {{ $.Values.namespace }}
roleRef:
  kind: Role
  name: {{ .name }}
  apiGroup: rbac.authorization.k8s.io
---
{{- end }}
